In [5]:
#1 >> Create a numPy array 'arr' of integer from 0 to 5 and print its data type.
import numpy as np
import random

In [416]:
arr=np.arange(0,6) # To find the number in sequential order

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [417]:
arr.dtype  # To find the data type

dtype('int64')

In [9]:
#2 >>>> Given a numPy array 'arr',check if its data type is float64.
arr=np.array([1.5,2.6,3.7])

In [10]:
arr

array([1.5, 2.6, 3.7])

In [11]:
arr.dtype

dtype('float64')

In [12]:
# yes the data type is float64

In [13]:
#3 >>>> Create a numPy array 'arr' with a data type of complex 128 cointaining three complex number.
list1=[5+6j,8+5j,9+2j]

In [14]:
arr=np.asarray(list1)

In [15]:
arr

array([5.+6.j, 8.+5.j, 9.+2.j])

In [16]:
arr.dtype

dtype('complex128')

In [17]:
#4 >>>> Convert an existing numPy array 'arr' of integers to float32 data type.
arr=np.arange(1,5)

In [18]:
arr

array([1, 2, 3, 4])

In [19]:
arr.dtype

dtype('int64')

In [418]:
arr1=arr.astype(np.float32) # To changfe the data type of an array

In [21]:
arr1

array([1., 2., 3., 4.], dtype=float32)

In [22]:
arr1.dtype

dtype('float32')

In [23]:
#5 >>>>> Given a numpy array 'arr' with float64 data type, convert it into float32 to reduce the decimal precision.
list2=[1.55,1.43,1.31,1.23]

In [24]:
arr1=np.asarray(list2)

In [25]:
arr1

array([1.55, 1.43, 1.31, 1.23])

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr=arr1.astype(np.float32)

In [28]:
arr

array([1.55, 1.43, 1.31, 1.23], dtype=float32)

In [29]:
#6 >>>>> Write a function array_attributes that takes a numPy array as input and return its shape,size and data type.

In [419]:
def Arr_attributes(arr):
    shape=arr.shape
    size=arr.size
    datatype=arr.dtype
    return shape, size, datatype
    
    

In [420]:
arr=np.asarray([1,2,3,4,5])

In [421]:
Arr_attributes(arr)

((5,), 5, dtype('int64'))

In [422]:
#7  >>> Create a function array_dimension that takes a numPy array as input and return its dimensionally.
def Array_dimension(arr):
    dimension=arr.ndim
    return dimension

In [34]:
arr=np.asarray([1,2,3])

In [423]:
Array_dimension(arr)

1

In [36]:
#8 >>> Design a function item_size_info that takes a nimPy array as input and returns the items size and the total size in bytes

In [425]:
def Item_size_info(arr):
    item_size=arr.byteswap()
    total_size=arr.nbytes
    return item_size,total_size

In [426]:
arr=np.asarray([1,3,4,5,6,7,8])

In [427]:
Item_size_info(arr)

(array([ 72057594037927936, 216172782113783808, 288230376151711744,
        360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488]),
 56)

In [428]:
#9 >>>> Create a function that array_strides that takes a numPy array as input and return the strides of the array.
def Array_strides(arr):
    strides=arr.strides
    return strides

In [429]:
Array_strides(np.asarray([1,2,3,45]))

(8,)

In [42]:
#10 >>>>> Design a function shape_stride_relationship that takes a numPy array as input and return the shape and strides of the array

In [431]:
def Shape_stride_relationship(arr):
    shape=arr.shape
    strides=arr.strides
    return shape,strides

In [432]:
Shape_stride_relationship(np.asarray([1,2,3,44]))

((4,), (8,))

In [45]:
#11. Create  a function 'create_ones_matrix' that takes an integer 'n' as input and return a NumPy array of zeros with 'n' elements.

In [433]:
def Create_ones_matrix(n):
    matrix=np.zeros(n)
    return matrix

In [434]:
Create_ones_matrix(5)

array([0., 0., 0., 0., 0.])

In [48]:
#12 >>>>> Write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as input and generates a 2D NumPy array filled with ones of size "rows*cols".

In [436]:
def Create_ones_matrix(n,m):
    matrix=np.ones((n,m))
    return matrix

In [437]:
Create_ones_matrix(2,2)

array([[1., 1.],
       [1., 1.]])

In [51]:
#13 >>>> Write a function 'generate_range_array' that takes three integers start,stops,and steps as arguments and creates a NumPy array with a range strating from 'start',ending or stop(exclusive),and with the specified 'steps'.

In [438]:
def Generate_range_array(start,stop,step):
    number=np.arange(start,stop,step)
    return number

In [439]:
Generate_range_array(1,5,2)

array([1, 3])

In [54]:
#14 >>>> Design a function 'generate_linear_space' that takes two float 'start','stop' and an integer 'num' as arguments and generates a Numpy array wiyh num equally spaced vlaues between 'start'and 'stop'(inclusive).

In [440]:
def Generate_linear_space(start,stop):
    matrix=np.arange(start,stop)
    return matrix

In [441]:
Generate_linear_space(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#15 >>>> Create a function "create_identity_matrix" that takes an integer 'n' as input and generates a square identity matrix of size 'n*n" using numpy.eye

In [442]:
def Create_identity_matrix(n,m):
    matrix=np.eye(n,m)
    return matrix

In [443]:
Create_identity_matrix(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
#16 >>> Write a function that takes a python list and convert it into a NumPy array.

In [444]:
def Covert_list(list1):
    arr=np.asarray(list1)
    return arr

In [446]:
Covert_list([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [63]:
arr.dtype

dtype('int64')

In [64]:
#17 >>>>> Create a NumPy array and demonstrate the used of 'numpy.view' to create a new array object with the same data.
list4=[11,22,33,45]
arr=np.asarray(list4)

In [65]:
arr.view()

array([11, 22, 33, 45])

In [66]:
#18 >>> Write a function that takes two NumPy arrays and concentenates them along a specified axis.
arr1=np.asarray([[2,4],[6,8]])

In [67]:
arr2=np.asarray([[3,4],[4,8]])

In [68]:
np.concatenate((arr1,arr2),axis=0)

array([[2, 4],
       [6, 8],
       [3, 4],
       [4, 8]])

In [447]:
#18 >>> Write a function that takes two NumPy arrays and concentenates them along a specified axis.
def Conc(arr1,arr2):
    conc1=np.concatenate((arr1,arr2),axis=0)
    return conc1
    
    

In [448]:
Conc(np.asarray([[2,4],[6,8]]),np.asarray([[3,4],[4,8]]))

array([[2, 4],
       [6, 8],
       [3, 4],
       [4, 8]])

In [71]:
#19 >>>> Create two numpy array with different shapes and concatenate them horizontally using 'numpy.concatenate'.

In [72]:
arr1=np.ones((2,2))

In [73]:
arr1

array([[1., 1.],
       [1., 1.]])

In [74]:
arr2=np.zeros((3,3))

In [75]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.concatenate((arr1,arr2),axis=None)

array([1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
#20 >>>>> Write a function that vertically stacks muntiple numpy arrays given in a list.
a=np.zeros((2,3))
b=np.ones((2,3))


In [78]:
np.concatenate((a,b),axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
#21 >>>> Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [449]:
def Create_arr(a,b,c):
    arr1=np.arange(a,b,c)
    return arr1

In [450]:
Create_arr(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [82]:
#22   >>>>>  Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [451]:
def Esf():
    number=np.linspace(0,1,10)
    return number

In [452]:
Esf()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [85]:
#23 >>>>   Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [453]:
def Log():
    numbers=np.logspace(1,1000,5)
    return numbers

In [454]:
Log()

/opt/conda/lib/python3.10/site-packages/numpy/core/function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [88]:
#24 >>>>>  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [89]:
np.random.randint(1,100,size=(5,3))

array([[40, 50, 32],
       [22, 79, 32],
       [68, 87, 71],
       [91, 68, 50],
       [62, 61, 62]])

In [90]:
#25 >>>>> Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [455]:
import pandas as pd
def Replace_negatives_with_zeros(df, column_name):
    
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

In [456]:
data = {'A': [1, -2, 3, -4, 5], 'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)

In [458]:
Replace_negatives_with_zeros(df, "A"and"B")

A   B
0  1  10
1 -2   0
2  3  30
3 -4   0
4  5  50

In [94]:
#26 >>>>>>Access the 3rd element from the given NumPy array.

In [95]:
arr = np.array([10, 20, 30, 40, 50])

In [96]:
arr[2]

30

In [97]:
#27 >>>>>  Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [98]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
arr_2d[1,2]

6

In [100]:
#28 >>>>>. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])


In [101]:
arr

array([ 3,  8,  2, 10,  5,  7])

In [102]:
arr[arr>5]

array([ 8, 10,  7])

In [103]:
#29 >>>>   Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [104]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr[2:5]

array([3, 4, 5])

In [106]:
#30 >>>>>>  Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [107]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [109]:
#31 >>>  Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [110]:
def extract_elements_by_indices(arr_2d, indices):
    """
    Extracts elements from a 2D array based on given indices.

    Parameters:
    arr_2d (numpy.ndarray): The input 2D array.
    indices (list or numpy.ndarray): An array of tuples where each tuple contains the row and column index.

    Returns:
    numpy.ndarray: A 1D array of extracted elements.
    """
    # Extract rows and columns separately from the indices
    rows, cols = zip(*indices)
    # Use advanced indexing to extract the elements
    return arr_2d[rows, cols]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = [(0, 2), (1, 0), (2, 1)]

extracted_elements = extract_elements_by_indices(arr_2d, indices)
print(f"Extracted elements: {extracted_elements}")


Extracted elements: [3 4 8]


In [111]:
#32 >>>>>  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [112]:
arr=np.random.randint(1,8,5)
def filter(arr):
    arr1=arr[arr>2]
    return arr1

In [113]:
filter(arr)

array([5, 6, 5, 5])

In [114]:
#33 >>>>> Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension. 

In [115]:
arr1 = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
def extract_element(arr1,x,y,z):
    if not (len(x) == len(y) == len(z)):
        raise ValueError("All index arrays must have the same length")
    return arr1[x,y,z]

In [116]:
extract_element(arr1,[0,0,1],[1,2,1],[1,3,1])

array([ 6, 12, 18])

In [117]:
#34 >>>>>Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [118]:
def extract_elements_with_conditions(arr, condition1, condition2):
    """
    Extracts elements from an array where both conditions are satisfied.

    Parameters:
    arr (numpy.ndarray): The input array.
    condition1 (callable): A function that takes an element and returns a boolean for the first condition.
    condition2 (callable): A function that takes an element and returns a boolean for the second condition.

    Returns:
    numpy.ndarray: An array of elements that satisfy both conditions.
    """
    # Apply the conditions to the array
    boolean_mask = np.vectorize(condition1)(arr) & np.vectorize(condition2)(arr)
    
    # Use the boolean mask to extract elements
    return arr[boolean_mask]

# Example usage
arr = np.array([3, 8, 2, 10, 5, 7])

# Define conditions
condition1 = lambda x: x > 5  # Elements greater than 5
condition2 = lambda x: x % 2 == 0  # Elements that are even

extracted_elements = extract_elements_with_conditions(arr, condition1, condition2)
print("Extracted elements:", extracted_elements)


Extracted elements: [ 8 10]


In [119]:
#35 >>>>> . Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


In [120]:
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    """
    Extracts elements from a 2D array based on given row and column indices.

    Parameters:
    arr_2d (numpy.ndarray): The input 2D array.
    row_indices (list or numpy.ndarray): Indices for the rows.
    col_indices (list or numpy.ndarray): Indices for the columns.

    Returns:
    numpy.ndarray: An array of extracted elements.
    """
    if len(row_indices) != len(col_indices):
        raise ValueError("Row indices and column indices must have the same length")

    # Use advanced indexing to extract the elements
    return arr_2d[row_indices, col_indices]

# Example usage
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row_indices = [0, 1, 2]
col_indices = [2, 0, 1]

extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [3 4 8]


In [121]:
#36 >>>>>  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [122]:
arr=np.zeros((3,3))

In [123]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
arr_new=arr+5

In [125]:
arr_new

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [126]:
#37 >>>>>>Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [127]:
arr1=np.array([2,3,4])

In [128]:
arr1.shape

(3,)

In [129]:
arr2=np.array([1,5,7])

In [130]:
arr2.shape

(3,)

In [131]:
arr3=arr1*arr2

In [132]:
arr3

array([ 2, 15, 28])

In [133]:
#38 >>>>> Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [134]:
a=np.array([1,2,3,4])

In [135]:
arr5=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [136]:
arr5.shape

(3, 4)

In [137]:
arr5+a

array([[ 2,  4,  6,  8],
       [ 3,  5,  7,  9],
       [ 4,  6,  8, 10]])

In [138]:
#39 >>>>>> Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.


In [139]:
ar1=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [140]:
arr1.shape

(3,)

In [141]:
ar2=np.array([[1],[2],[3]])

In [142]:
ar2.shape

(3, 1)

In [143]:
ar1+ar2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [144]:
#40 >>>>>>. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [145]:
ar3=np.array([[1,2,3],[2,3,4]])

In [146]:
ar3.shape

(2, 3)

In [147]:
ar5=ar3.T # we manupulated the muntiplication by taking transpose and make muntiplication happen.

In [148]:
# For muntiplication of array coloumn of first row and row of second row must be equal,thats why take transpose.

In [149]:
ar4=np.array([[2,3],[2,6]])

In [150]:
ar4.shape

(2, 2)

In [151]:
ar3@ar5

array([[14, 20],
       [20, 29]])

In [152]:
#41  >>>>>> Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [153]:
np.mean(arr,axis=1)

array([2., 5.])

In [154]:
#42 >>>>>> Find maximum value in each row of the given array:
np.max(arr,axis=0)

array([4, 5, 6])

In [155]:
#43 >>>>>>  For the given array, find indices of maximum value in each column.
np.argmax(arr,axis=1)

array([2, 2])

In [156]:
#44 >>>>>> For the given array, apply custom function to calculate moving sum along rows.

In [157]:
import numpy as np

def moving_sum(arr, window_size):
    """
    Calculate the moving sum along the rows of a 2D array.

    Parameters:
    arr (numpy.ndarray): The input 2D array.
    window_size (int): The size of the moving window.

    Returns:
    numpy.ndarray: A 2D array with the moving sums calculated along the rows.
    """
    if window_size < 1:
        raise ValueError("Window size must be at least 1")

    # Initialize an array to store the moving sums
    moving_sums = np.zeros_like(arr, dtype=float)
    
    # Calculate the moving sums along each row
    for row_index in range(arr.shape[0]):
        row = arr[row_index]
        for i in range(len(row)):
            if i < window_size - 1:
                # For the initial elements where the window is not fully covered
                moving_sums[row_index, i] = np.sum(row[:i+1])
            else:
                # For elements where the window is fully covered
                moving_sums[row_index, i] = np.sum(row[i-window_size+1:i+1])
    
    return moving_sums

# Example usage
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

window_size = 3
result = moving_sum(arr, window_size)
print("Moving sums along rows with window size", window_size, ":")
print(result)


Moving sums along rows with window size 3 :
[[ 1.  3.  6.  9. 12.]
 [ 6. 13. 21. 24. 27.]
 [11. 23. 36. 39. 42.]]


In [158]:
#45 >>>>>>> In the given array, check if all elements in each column are even.

In [159]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [160]:
even_check=(arr%2==0)
even_column=np.all(even_check,axis=0)
print("Check if all elements in each column are even:", even_column)

Check if all elements in each column are even: [False False False]


In [161]:
#46 >>>>>Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.   

In [162]:
original_array = np.array([1, 2, 3, 4, 5, 6])

In [163]:
original_array.reshape(3,2)  # the product of row and column should always be same

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
#47 >>>>>  Create a function that takes a matrix as input and returns the flattened array.

In [165]:
def flatten_array(input_matrix):
    arr_new=input_matrix.flatten()
    return arr_new

In [166]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [167]:
flatten_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [168]:
#48 >>>>  Write a function that concatenates two given arrays along a specified axis.

In [169]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [170]:
np.concatenate((array1,array2),axis=0) # row wise concatenation

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [171]:
np.concatenate((array1,array2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [172]:
#49 >>>> Create a function that splits an array into multiple sub-arrays along a specified axis.

In [173]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [174]:
np.split(original_array,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [175]:
#50 >>>>  . Write a function that inserts and then deletes elements from a given array at specified indices.

In [176]:
original_array = np.array([1, 2, 3, 4, 5])

In [177]:
arr100=np.insert(original_array,[2,4],[10,11],axis=0)

In [178]:
arr100

array([ 1,  2, 10,  3,  4, 11,  5])

In [179]:
arr101=np.delete(original_array,[1,3],axis=0)

In [180]:
arr101

array([1, 3, 5])

In [181]:
#51 >>>>> Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [182]:
import random

In [183]:
arr1=np.random.randint(1,10,5)

In [184]:
arr1

array([6, 6, 3, 9, 9])

In [185]:
arr2=np.random.randint(1,10,5)

In [186]:
arr2

array([1, 1, 8, 9, 1])

In [187]:
arr1+arr2

array([ 7,  7, 11, 18, 10])

In [188]:
#52 >>>>>>Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [189]:
arr1=np.arange(1,10)

In [190]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
a=arr1[::-1]

In [192]:
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [193]:
arr2=np.arange(1,10)

In [194]:
b=arr2

In [195]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
arr2-arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [197]:
#53 >>>>Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [198]:
arr1=np.random.randint(1,10,5)

In [199]:
arr1

array([3, 4, 5, 2, 7])

In [200]:
arr2=np.random.randint(2,5,5)

In [201]:
arr2

array([2, 2, 4, 2, 4])

In [202]:
arr_new=arr1*arr2

In [203]:
arr_new

array([ 6,  8, 20,  4, 28])

In [204]:
#54 >>>>. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [205]:
arr1=np.random.randint(2,10,5)

In [206]:
arr1

array([8, 6, 2, 3, 6])

In [207]:
arr2=np.random.randint(1,5,5)

In [208]:
arr2

array([1, 2, 2, 1, 3])

In [209]:
arr1/arr2

array([8., 3., 1., 3., 2.])

In [210]:
#55 >>>>> Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [211]:
arr1=np.random.randint(1,5,5)

In [212]:
arr1

array([1, 1, 4, 1, 2])

In [213]:
arr2=arr1[::-1]

In [214]:
arr2

array([2, 1, 4, 1, 1])

In [215]:
arr1**arr2

array([  1,   1, 256,   1,   2])

In [216]:
#56 >>>>Write a function that counts the occurrences of a specific substring within a NumPy array of strings

In [217]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count(arr,element_to_count):
    c=0
    for i in arr:
        if i==element_to_count:
            c=c+1
    print(c)



In [218]:
count(arr,"hello")

3


In [219]:
#57 >>>>>Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [220]:
arr

array(['Hello', 'World', 'OpenAI', 'GPT'], dtype='<U6')

In [221]:
def extract(arr):
    for i in arr:
        if i==i.upper():
            print(i)
    
            

In [222]:
extract(arr)

GPT


In [223]:
#58 >>>> Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string

In [224]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [225]:
arr[2]="mango" # reolaced grape with mango

In [226]:
arr

array(['apple', 'banana', 'mango', 'pineapple'], dtype='<U9')

In [227]:
#59 >>>>>Write a function that concatenates strings in a NumPy array element-wise.

In [228]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [229]:
def conc(arr1,arr2):
    final_arr=np.char.add(arr1,arr2)
    return final_arr

In [230]:
conc(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [231]:
#60 >>>> Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [232]:
def find(arr):
    for i in arr:
        length=max(len(i) for i in arr)
    return length
        
    

In [233]:
find(arr)

9

In [234]:
#61. >>>>>> Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, andstandard deviation of the dataset using NumPy's functions.

In [235]:
ds=np.random.randint(1,1000,100)

In [236]:
import pandas as pd

In [237]:
pd.DataFrame(ds)

0
0   613
1   109
2   598
3   932
4   310
..  ...
95    4
96  214
97  272
98  367
99  316

[100 rows x 1 columns]

In [238]:
ds.mean()   # to find the mean

510.17

In [239]:
ds.var() # to find the variance

75817.4611

In [240]:
ds.std()  # to find the standard deviation

275.3497069183114

In [241]:
import statistics as st

In [242]:
st.median(ds) # to find the median of the dataset

499.0

In [243]:
#62 >>> Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [244]:
ds=np.random.randint(1,100,50)

In [245]:
df=pd.DataFrame(ds)

In [246]:
df.describe()

0
count  50.000000
mean   49.980000
std    29.958808
min     1.000000
25%    23.250000
50%    54.000000
75%    70.000000
max    99.000000

In [247]:
#here the 25 percentile is 30.5 and 75 percentile is 88.0

In [248]:
#63 >>>>> Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function

In [249]:
arr1=np.array([1,2,3,4])

In [250]:
arr2=np.array([2,4,6,8])

In [251]:
np.corrcoef(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

In [252]:
#64 >>>>>Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [253]:
matrix1=np.matrix([[1,2,3],[2,3,4],[2,3,5]])

In [254]:
matrix1

matrix([[1, 2, 3],
        [2, 3, 4],
        [2, 3, 5]])

In [255]:
matrix2=np.matrix([[2,3,4],[2,5,6],[5,7,9]])

In [256]:
matrix2

matrix([[2, 3, 4],
        [2, 5, 6],
        [5, 7, 9]])

In [257]:
matrix1.dot(matrix2)

matrix([[21, 34, 43],
        [30, 49, 62],
        [35, 56, 71]])

In [258]:
#65>>>>>Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [259]:
arr1=np.random.randint(10,1000,50)

In [260]:
arr1

array([912, 615, 549, 887, 804, 933, 990, 557, 516, 912, 211, 374, 116,
        94, 145, 248, 405, 289,  75, 555, 143, 624, 304, 149, 694, 823,
       121, 165, 545, 589, 792, 905, 459, 355, 971, 414,  23, 953, 269,
       736, 535, 342, 289,  91,  60, 444, 502, 536, 177, 196])

In [261]:
np.percentile(arr1,10)

113.80000000000001

In [262]:
np.percentile(arr1,50)

451.5

In [263]:
np.percentile(arr1,90)

912.0

In [264]:
np.percentile(arr1,25)

199.75

In [265]:
np.percentile(arr1,75)

676.5

In [266]:
#66 >>>>>  Create a NumPy array of integers and find the index of a specific element.

In [267]:
arr=np.array([1,2,3,4,5])

In [268]:
arr[2]

3

In [269]:
#67 >>>>Generate a random NumPy array and sort it in ascending order

In [270]:
arr=np.array([1,3,4,5,66,45,3,44,5,33,444,35,1543,333])

In [271]:
np.sort(arr)

array([   1,    3,    3,    4,    5,    5,   33,   35,   44,   45,   66,
        333,  444, 1543])

In [272]:
#68 >>>>>>Filter elements >20  in the given NumPy array.

In [273]:
arr = np.array([12, 25, 6, 42, 8, 30])

In [274]:
arr[arr>20]

array([25, 42, 30])

In [275]:
#69 >>>>>>> Filter elements which are divisible by 3 from a given NumPy array.

In [276]:
arr = np.array([1, 5, 8, 12, 15])

In [277]:
arr[arr%3==0]

array([12, 15])

In [278]:
#70 >>>Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array

In [279]:
arr = np.array([10, 20, 30, 40, 50])

In [280]:
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

In [281]:
#71 >>>>>For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [282]:
arr = np.array([1, 2, 3])

In [283]:
arr.dtype.byteorder

'='

In [284]:
#72 >>>> For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [285]:
arr = np.array([1, 2, 3], dtype=np.int32)


In [286]:
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [287]:
#73 >>>> For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

In [288]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [289]:
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype=int32)

In [290]:
#74 >>>> For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

In [291]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [292]:
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [293]:
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype=int32)

In [294]:
#75 >>>> For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

In [295]:
import numpy as np

# Define the array
arr = np.array([1, 2, 3], dtype=np.int32)

# Get the byte order of the array's dtype
byteorder = arr.dtype.byteorder

# Determine the native byte order of the system
import sys
native_byteorder = '<' if sys.byteorder == 'little' else '>'

# Check if byte swapping is necessary
if byteorder == '=':  # '=' means native byte order
    print("No byte swapping is necessary.")
elif byteorder != native_byteorder:
    print("Byte swapping is necessary.")
else:
    print("No byte swapping is necessary.")

# Print the byte order of the array and the system's native byte order
print(f"Array byte order: {byteorder}")
print(f"System native byte order: {native_byteorder}")


No byte swapping is necessary.
Array byte order: =
System native byte order: <


In [296]:
"""76 >>> Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`."""

'76 >>> Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify\nan element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.'

In [339]:
arr1=np.array([1,2,4,5,7,8])

In [340]:
copy_arr=arr1.copy()

In [341]:
copy_arr

array([1, 2, 4, 5, 7, 8])

In [342]:
copy_arr[0]=11

In [343]:
copy_arr

array([11,  2,  4,  5,  7,  8])

In [344]:
if np.array_equal(arr1, copy_arr):
    print("Modifying copy_arr affects arr1.")
else:
    print("Modifying copy_arr does not affect arr1.")

Modifying copy_arr does not affect arr1.


In [303]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`

In [345]:
arr=np.random.rand(3,3)

In [346]:
new_mat=np.matrix(arr)

In [347]:
new_mat

matrix([[0.65845156, 0.49840348, 0.48123117],
        [0.22724828, 0.72893313, 0.91538398],
        [0.98881268, 0.91102464, 0.8459319 ]])

In [348]:
view_slice=new_mat[:2,:2]

In [349]:
view_slice

matrix([[0.65845156, 0.49840348],
        [0.22724828, 0.72893313]])

In [350]:
view_slice[0,0]=100

In [351]:
view_slice

matrix([[100.        ,   0.49840348],
        [  0.22724828,   0.72893313]])

In [353]:
new_mat

matrix([[100.        ,   0.49840348,   0.48123117],
        [  0.22724828,   0.72893313,   0.91538398],
        [  0.98881268,   0.91102464,   0.8459319 ]])

In [357]:
# yes it alter the new_mat

In [312]:
#78 >>>>create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [314]:
array_a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [315]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [316]:
view_b=array_a[:2,:2]

In [317]:
view_b

array([[1, 2],
       [4, 5]])

In [318]:
view_b+5  # broadcast the addition of 5

array([[ 6,  7],
       [ 9, 10]])

In [319]:
#There is no alter to the array_a

In [320]:
#79 >>>>>Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped vie`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [323]:
orig_array=np.array([[1,2,3,4],[5,6,7,8]])

In [324]:
reshaped_view=orig_array.reshape(4,2)

In [326]:
reshaped_view

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [328]:
reshaped_view.shape

(4, 2)

In [329]:
reshaped_view[0,1]=121

In [333]:
reshaped_view

array([[  1, 121],
       [  3,   4],
       [  5,   6],
       [  7,   8]])

In [334]:
orig_array

array([[  1, 121,   3,   4],
       [  5,   6,   7,   8]])

In [358]:
# yes the rehsaped_view alter the orig_array

In [360]:
#80 >>>>>>>>Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [373]:
data=np.random.randint(0,10,(3,4))

In [374]:
data

array([[7, 7, 2, 2],
       [1, 8, 2, 8],
       [7, 3, 9, 3]])

In [375]:
data_copy=data[data>5]

In [376]:
data_copy

array([7, 7, 8, 8, 7, 9])

In [377]:
data_copy[4]=22

In [378]:
data_copy

array([ 7,  7,  8,  8, 22,  9])

In [379]:
data

array([[7, 7, 2, 2],
       [1, 8, 2, 8],
       [7, 3, 9, 3]])

In [380]:
# There is no change in the data due to change in the data_copy

In [381]:
#81 >>>>> Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [382]:
matrix1=np.matrix([[1,2,3],[2,3,4],[2,4,8]])

In [383]:
matrix2=np.matrix([[2,3,4],[4,5,7],[1,2,4]])

In [384]:
matrix1+matrix2  # addition

matrix([[ 3,  5,  7],
        [ 6,  8, 11],
        [ 3,  6, 12]])

In [385]:
matrix2-matrix1  # subtraction

matrix([[ 1,  1,  1],
        [ 2,  2,  3],
        [-1, -2, -4]])

In [386]:
#82 >>>>> Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [387]:
a=np.random.randint(1,10,(3,2))

In [388]:
a

array([[6, 9],
       [3, 1],
       [6, 6]])

In [389]:
matrix1=np.matrix(a)

In [390]:
matrix1

matrix([[6, 9],
        [3, 1],
        [6, 6]])

In [392]:
b=np.random.randint(2,8,(2,3))

In [393]:
matrix2=np.matrix(b)

In [394]:
matrix2

matrix([[7, 7, 3],
        [3, 4, 7]])

In [395]:
matrix1@matrix2

matrix([[69, 78, 81],
        [24, 25, 16],
        [60, 66, 60]])

In [396]:
 #83.Create a matrix `E` and find its transpose

In [397]:
E=np.matrix([[1,2,3],[1,3,4],[1,3,5]])

In [400]:
E

matrix([[1, 2, 3],
        [1, 3, 4],
        [1, 3, 5]])

In [401]:
transpose_E=E.T

In [402]:
transpose_E

matrix([[1, 1, 1],
        [2, 3, 3],
        [3, 4, 5]])

In [403]:
#84 >>>> Generate a square matrix `F` and compute its determinant.

In [411]:
F=np.matrix([[1,5,3],[4,5,6],[7,8,9]])

In [412]:
np.linalg.det(F)

18.000000000000014

In [413]:
#85 >>>>Create a square matrix `G` and find its inverse.

In [414]:
G=np.matrix([[2,3,4],[4,6,7],[1,4,7]])

In [415]:
np.linalg.inv(G)

matrix([[ 2.8, -1. , -0.6],
        [-4.2,  2. ,  0.4],
        [ 2. , -1. ,  0. ]])